export const products = [
  {
    id: "1",
    name: "Samsung Galaxy S23 Ultra",
    price: 325000,
    image: "/placeholder.svg?height=300&width=300",
    category: "Smartphones",
    rating: 4.8,
    reviews: 124,
    featured: true,
    sku: "SM-S23U-256-BLK",
    description: "The ultimate smartphone with a powerful camera and S Pen.",
    fullDescription:
      "Experience the power of Galaxy S23 Ultra. With the highest camera resolution on a phone, you can take clear, detailed photos that remain sharp even when you crop in. Create gallery-worthy content with multiple cameras and pro-grade settings. Write, sketch and edit with the built-in S Pen. And do it all on the fastest Snapdragon processor we've ever put in a Galaxy.",
    specifications: [
      { name: "Display", value: "6.8-inch Dynamic AMOLED 2X" },
      { name: "Processor", value: "Snapdragon 8 Gen 2" },
      { name: "RAM", value: "12GB" },
      { name: "Storage", value: "256GB" },
      { name: "Battery", value: "5000mAh" },
      { name: "Camera", value: "200MP + 12MP + 10MP + 10MP" },
      { name: "OS", value: "Android 13" },
    ],
    reviewsList: [
      { author: "Kasun P.", rating: 5, comment: "Best phone I've ever owned. The camera is incredible!" },
      { author: "Dilini S.", rating: 4, comment: "Great phone but a bit expensive." },
      { author: "Chamara J.", rating: 5, comment: "The S Pen is a game changer for productivity." },
    ],
    images: [
      "/placeholder.svg?height=500&width=500",
      "/placeholder.svg?height=500&width=500",
      "/placeholder.svg?height=500&width=500",
      "/placeholder.svg?height=500&width=500",
    ],
  },
  {
    id: "2",
    name: "Apple iPhone 14 Pro Max",
    price: 350000,
    image: "/placeholder.svg?height=300&width=300",
    category: "Smartphones",
    rating: 4.7,
    reviews: 98,
    featured: true,
    sku: "IP-14PM-256-GLD",
    description: "Apple's flagship smartphone with Dynamic Island and A16 Bionic chip.",
    fullDescription:
      "iPhone 14 Pro Max. Capture incredible detail with a 48MP Main camera. Experience iPhone in a whole new way with Dynamic Island and Always-On display. And get peace of mind with groundbreaking safety features.",
    specifications: [
      { name: "Display", value: "6.7-inch Super Retina XDR" },
      { name: "Processor", value: "A16 Bionic" },
      { name: "RAM", value: "6GB" },
      { name: "Storage", value: "256GB" },
      { name: "Battery", value: "4323mAh" },
      { name: "Camera", value: "48MP + 12MP + 12MP" },
      { name: "OS", value: "iOS 16" },
    ],
    reviewsList: [
      { author: "Nuwan R.", rating: 5, comment: "The Dynamic Island is such a clever feature!" },
      { author: "Amali F.", rating: 4, comment: "Great phone but I wish it had USB-C." },
      { author: "Saman W.", rating: 5, comment: "The camera quality is outstanding." },
    ],
    images: [
      "/placeholder.svg?height=500&width=500",
      "/placeholder.svg?height=500&width=500",
      "/placeholder.svg?height=500&width=500",
      "/placeholder.svg?height=500&width=500",
    ],
  },
  {
    id: "3",
    name: "Dell XPS 15 Laptop",
    price: 420000,
    image: "/placeholder.svg?height=300&width=300",
    category: "Laptops",
    rating: 4.6,
    reviews: 76,
    featured: true,
    discount: 10,
    sku: "DL-XPS15-i7-16GB",
    description: "Powerful laptop with stunning display and premium build quality.",
    fullDescription:
      "The Dell XPS 15 features a stunning 15.6-inch InfinityEdge display, powerful Intel Core i7 processor, NVIDIA GeForce RTX graphics, and premium build quality with machined aluminum and carbon fiber. Perfect for professionals, content creators, and anyone who needs a high-performance laptop.",
    specifications: [
      { name: "Display", value: "15.6-inch 4K UHD+ (3840 x 2400)" },
      { name: "Processor", value: "Intel Core i7-12700H" },
      { name: "RAM", value: "16GB DDR5" },
      { name: "Storage", value: "1TB SSD" },
      { name: "Graphics", value: "NVIDIA GeForce RTX 3050 Ti" },
      { name: "Battery", value: "86Whr" },
      { name: "OS", value: "Windows 11 Pro" },
    ],
    reviewsList: [
      { author: "Pradeep K.", rating: 5, comment: "The build quality is exceptional. Worth every rupee." },
      { author: "Malini T.", rating: 4, comment: "Great performance but runs a bit hot under load." },
      { author: "Roshan P.", rating: 5, comment: "The display is absolutely gorgeous!" },
    ],
    images: [
      "/placeholder.svg?height=500&width=500",
      "/placeholder.svg?height=500&width=500",
      "/placeholder.svg?height=500&width=500",
      "/placeholder.svg?height=500&width=500",
    ],
  },
  {
    id: "4",
    name: "Sony WH-1000XM5 Headphones",
    price: 85000,
    image: "/placeholder.svg?height=300&width=300",
    category: "Audio",
    rating: 4.9,
    reviews: 112,
    featured: true,
    sku: "SN-WH1000XM5-BLK",
    description: "Industry-leading noise cancellation with exceptional sound quality.",
    fullDescription:
      "Sony's WH-1000XM5 headphones deliver industry-leading noise cancellation and exceptional sound quality. With 8 microphones and 2 processors, they offer unprecedented noise cancellation. The newly developed driver unit provides stunning sound quality, while the lightweight design ensures all-day comfort.",
    specifications: [
      { name: "Driver", value: "30mm" },
      { name: "Battery Life", value: "Up to 30 hours" },
      { name: "Charging Time", value: "3.5 hours" },
      { name: "Bluetooth", value: "5.2" },
      { name: "Weight", value: "250g" },
      { name: "Noise Cancellation", value: "Yes, Adaptive" },
      { name: "Microphones", value: "8 microphones with 2 processors" },
    ],
    reviewsList: [
      { author: "Dinesh M.", rating: 5, comment: "The noise cancellation is simply magical." },
      { author: "Kumari L.", rating: 5, comment: "Sound quality is exceptional, worth every rupee." },
      { author: "Tharindu S.", rating: 4, comment: "Great headphones but the case is a bit bulky." },
    ],
    images: [
      "/placeholder.svg?height=500&width=500",
      "/placeholder.svg?height=500&width=500",
      "/placeholder.svg?height=500&width=500",
      "/placeholder.svg?height=500&width=500",
    ],
  },
  {
    id: "5",
    name: "LG C2 65-inch OLED TV",
    price: 450000,
    image: "/placeholder.svg?height=300&width=300",
    category: "TVs",
    rating: 4.8,
    reviews: 65,
    featured: true,
    discount: 15,
    sku: "LG-C2-65-OLED",
    description: "Stunning OLED TV with perfect blacks and vibrant colors.",
    fullDescription:
      "The LG C2 65-inch OLED TV delivers stunning picture quality with perfect blacks, infinite contrast, and over a billion colors. Powered by the α9 Gen5 AI Processor 4K, it adapts to what you're watching to deliver the best picture and sound. With NVIDIA G-SYNC, AMD FreeSync Premium, and VRR, it's also perfect for gaming.",
    specifications: [
      { name: "Display", value: "65-inch OLED evo" },
      { name: "Resolution", value: "4K UHD (3840 x 2160)" },
      { name: "Processor", value: "α9 Gen5 AI Processor 4K" },
      { name: "HDR", value: "Dolby Vision, HDR10, HLG" },
      { name: "Refresh Rate", value: "120Hz" },
      { name: "HDMI", value: "4x HDMI 2.1" },
      { name: "Smart TV", value: "webOS 22" },
    ],
    reviewsList: [
      { author: "Lakmal P.", rating: 5, comment: "The picture quality is absolutely breathtaking." },
      { author: "Shamali D.", rating: 5, comment: "Perfect for movies and gaming." },
      { author: "Ruwan J.", rating: 4, comment: "Great TV but the webOS interface could be better." },
    ],
    images: [
      "/placeholder.svg?height=500&width=500",
      "/placeholder.svg?height=500&width=500",
      "/placeholder.svg?height=500&width=500",
      "/placeholder.svg?height=500&width=500",
    ],
  },
  {
    id: "6",
    name: "Apple iPad Pro 12.9-inch",
    price: 275000,
    image: "/placeholder.svg?height=300&width=300",
    category: "Tablets",
    rating: 4.7,
    reviews: 89,
    sku: "AP-IPADPRO-12-M2",
    description: "Powerful tablet with M2 chip and stunning Liquid Retina XDR display.",
    fullDescription:
      "The 12.9-inch iPad Pro features the breakthrough M2 chip, an advanced Liquid Retina XDR display, superfast wireless connectivity, and next-generation Apple Pencil capabilities. With all-day battery life, it's perfect for creative professionals, students, and anyone who needs a powerful and portable device.",
    specifications: [
      { name: "Display", value: "12.9-inch Liquid Retina XDR" },
      { name: "Processor", value: "Apple M2" },
      { name: "Storage", value: "256GB" },
      { name: "RAM", value: "8GB" },
      { name: "Camera", value: "12MP Wide + 10MP Ultra Wide" },
      { name: "Battery", value: "Up to 10 hours" },
      { name: "OS", value: "iPadOS 16" },
    ],
    reviewsList: [
      { author: "Nimal S.", rating: 5, comment: "The M2 chip is incredibly powerful." },
      { author: "Kamala R.", rating: 4, comment: "Great tablet but expensive accessories." },
      { author: "Ajith P.", rating: 5, comment: "The display is perfect for photo editing." },
    ],
    images: [
      "/placeholder.svg?height=500&width=500",
      "/placeholder.svg?height=500&width=500",
      "/placeholder.svg?height=500&width=500",
      "/placeholder.svg?height=500&width=500",
    ],
  },
  {
    id: "7",
    name: "Canon EOS R6 Mark II",
    price: 520000,
    image: "/placeholder.svg?height=300&width=300",
    category: "Cameras",
    rating: 4.8,
    reviews: 42,
    sku: "CN-EOSR6M2-BDY",
    description: "Professional mirrorless camera with exceptional image quality and speed.",
    fullDescription:
      "The Canon EOS R6 Mark II is a professional-grade mirrorless camera that delivers exceptional image quality and speed. With a 24.2MP full-frame CMOS sensor, DIGIC X processor, and up to 40 fps continuous shooting, it's perfect for action, wildlife, and sports photography. It also features 6K RAW external recording and 4K60p internal recording for videographers.",
    specifications: [
      { name: "Sensor", value: "24.2MP Full-Frame CMOS" },
      { name: "Processor", value: "DIGIC X" },
      { name: "Autofocus", value: "Dual Pixel CMOS AF II" },
      { name: "ISO Range", value: "100-102400 (expandable to 204800)" },
      { name: "Continuous Shooting", value: "Up to 40 fps" },
      { name: "Video", value: "4K60p, 6K RAW external" },
      { name: "Image Stabilization", value: "In-body, up to 8 stops" },
    ],
    reviewsList: [
      { author: "Prasad K.", rating: 5, comment: "The autofocus system is incredibly accurate and fast." },
      { author: "Nilmini J.", rating: 5, comment: "Perfect camera for both photography and videography." },
      { author: "Chandana R.", rating: 4, comment: "Great camera but battery life could be better." },
    ],
    images: [
      "/placeholder.svg?height=500&width=500",
      "/placeholder.svg?height=500&width=500",
      "/placeholder.svg?height=500&width=500",
      "/placeholder.svg?height=500&width=500",
    ],
  },
  {
    id: "8",
    name: "Samsung 49-inch Odyssey G9 Gaming Monitor",
    price: 320000,
    image: "/placeholder.svg?height=300&width=300",
    category: "Monitors",
    rating: 4.6,
    reviews: 38,
    sku: "SM-G9-49-QLED",
    description: "Ultra-wide curved gaming monitor with stunning QLED display.",
    fullDescription:
      "The Samsung Odyssey G9 is the ultimate gaming monitor, featuring a massive 49-inch 1000R curved QLED display with Dual QHD resolution (5120x1440). With a 240Hz refresh rate, 1ms response time, and G-Sync/FreeSync Premium Pro support, it delivers an immersive gaming experience like no other. The futuristic design with Infinity Core lighting adds a touch of style to any gaming setup.",
    specifications: [
      { name: "Display", value: "49-inch QLED" },
      { name: "Resolution", value: "5120x1440 (Dual QHD)" },
      { name: "Refresh Rate", value: "240Hz" },
      { name: "Response Time", value: "1ms" },
      { name: "Curvature", value: "1000R" },
      { name: "HDR", value: "HDR1000" },
      { name: "Adaptive Sync", value: "G-Sync Compatible, FreeSync Premium Pro" },
    ],
    reviewsList: [
      {
        author: "Gihan S.",
        rating: 5,
        comment: "The immersion is unbelievable. It's like having two 27-inch monitors without the bezels.",
      },
      {
        author: "Thilini M.",
        rating: 4,
        comment: "Amazing monitor but requires a powerful GPU to run games at full resolution.",
      },
      { author: "Kasun W.", rating: 5, comment: "The curve is perfect for productivity and gaming." },
    ],
    images: [
      "/placeholder.svg?height=500&width=500",
      "/placeholder.svg?height=500&width=500",
      "/placeholder.svg?height=500&width=500",
      "/placeholder.svg?height=500&width=500",
    ],
  },
]
